### ISSUE TITLE
Is this project available on Windows 10

### ISSUE THREAD

**Issue by benchrus** [HowieMa/CVTHead#1]
Hi, I am interested in this project and I found Assertion Error while running on Windows 10.
The error is like this:
```
(cvthead) E:\Workspace\aqua\CVTHead>python inference.py --src_pth examples/1.png --drv_pth examples/2.png --out_pth examples/output.png --ckpt_pth data/cvthead.pt
 ************ Load pre-traiend Face Parsing Model ************
************ Load pre-traiend Hair+Shoulder Deformation Model ************


 ************ Load pre-traiend DECA ************
C:\Users\Administrator\anaconda3\envs\cvthead\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\Administrator\anaconda3\envs\cvthead\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Traceback (most recent call last):
  File "E:\Workspace\aqua\CVTHead\inference.py", line 95, in <module>
    main(args)
  File "E:\Workspace\aqua\CVTHead\inference.py", line 75, in main
    model = CVTHead()                                        # cpu model
  File "E:\Workspace\aqua\CVTHead\models\cvthead.py", line 150, in __init__
    self.deca = DECA(config=deca_cfg)
  File "E:\Workspace\aqua\CVTHead\decalib\deca.py", line 50, in __init__
    self._create_model(self.cfg.model)
  File "E:\Workspace\aqua\CVTHead\decalib\deca.py", line 81, in _create_model
    self.E_flame = ResnetEncoder(outsize=self.n_param).to(self.device)
  File "C:\Users\Administrator\anaconda3\envs\cvthead\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "C:\Users\Administrator\anaconda3\envs\cvthead\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Administrator\anaconda3\envs\cvthead\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Administrator\anaconda3\envs\cvthead\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\Administrator\anaconda3\envs\cvthead\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\Administrator\anaconda3\envs\cvthead\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by HowieMa** [comment]
Hi, thanks for your interests in this project. 
It may be available on Win10. Unfortunately, I don't have a device with Win10 to verify it at this time. 
The error you get comes from CUDA side. It seems that you don't installed a Pytorch with correct cuda, or you don't have GPUs. It is not the bugs from the project side.

**Comment by benchrus** [comment]
Thanks for the answer, I have NVIDIA A40, installed torch=2.0.0, cuda 11.7.
I'll check. Thanks again.
